### PR TITLE
big chungus outstanding move

### LINKED ISSUE #578: hide cursor in fullscreen after a timeout
see #553 for suggestion

should behave like fullscreen video player (youtube, etc.)

### PR DESCRIPTION
**Pull request by breja**
## MOST ANNOYING BUG OF 2019
- [ ] terminal scroll still broekn help help how do i fix this i can't repro
  - [x] added debug logging so next time it happens I WILL BE PREPARED
you-are-not-prepared

## TODO
- [x] refresh/redraw when switching between hidpi and regular monitors
- [ ] build binaries for mac
- [ ] build binaries for linux
- [ ] build binaries for windows 
- [x] when exit last vim instance the app does not quit (sometimes)
  - cant repro
- [x] i notice when resizing a 3-way split very tiny, we get lines going across the thing
  - not very important right now. deferring
- [x] jump to definition does not add jump to jumplist
  - consistent with previous stable veonim version behavior
  - jumping to another file adds to jumplist
  - jumping within the same file with `setCursor` does not add to jumplist. again, this is consistent with the previous stable version. opened #584 to track this
- [x] positions of popups sometimes wrong
  - the position calculation is correct, but we are not accounting for wrapping lines
- [x] remove `SourcePre` as it is causing more problems than it solves
- [x] fix highlight infos not working across terms in multiple instances
- [x] highlight info, default colors, etc. need to be scoped per instance. on instance switch need to reload highlights and textures atlas
  - [x] test in multiple instances
  - this happens if you open term in first instance, create a new instance, switch back to 1st and term colors are messed up (because the second instance overwrote highlights)
- [x] cursor char not always correct
- [x] webgl line width
- [x] mouse trap no move fullscreen
- [x] cursorline does not scale font height
- [x] dedup resize events
- [x] padding should not apply to cursorline
- [x] fresh neovim source merge with latest `ext_messages` and `ext_windows`
- [x] colorscheme switch statusline colors ALL OF THEM
- [x] cursor not always hiding for term windows when switching between tabs
- [x] make sure `guifont` switches correctly
  - [x] font face
  - [x] font size
- [x] guifont support list of fonts? possible?
  - maybe, need to do font detection which is hacky so i'll wait until someone complains
- [x] guifont support setting to blank or other invalid options uses builtin font
- [x] line height replacement
- [x] does it work on non-retina displays
- [x] make sure `colorscheme` switches correctly (i think webgl background does not update)

fixes #578

### CODE REVIEW

**Comment by khalidchawtany** [comment]
@breja how can I set font using this new pr?
the variables that were set in init.vim no more work

**Comment by breja** [comment]
Also the padding between lines is controlled with `linespace` (`:h linespace`)

Full font options example:
```vim
set guifont=SF\ Mono:h16
set linespace=10
```

**Comment by bfredl** [comment]
@breja 

in `msg_show`:

> // TODO: i think no msg kind means we don't show it??? or do we??
> if (!skind) return

no kind just means that it hasn't been assigned a kind yet, it should be still shown. Probably make sense to treat them as `NotifyKind.System`

**Comment by breja** [comment]
> @breja
> 
> in `msg_show`:
> 
> > // TODO: i think no msg kind means we don't show it??? or do we??
> > if (!skind) return
> 
> no kind just means that it hasn't been assigned a kind yet, it should be still shown. Probably make sense to treat them as `NotifyKind.System`

Makes sense, will do. Thanks for the explanation.

**Pull request merged**
